# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: count.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='count.proto',
  package='count',
  syntax='proto3',
  serialized_options=b'Z\"github.com/domage/grpc-queue/count',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x63ount.proto\x12\x05\x63ount\" \n\x08QRequest\x12\x14\n\x0cwordsToCount\x18\x01 \x01(\t\"\x1d\n\tQResultId\x12\x10\n\x08resultId\x18\x01 \x01(\x05\"\x1d\n\x07QResult\x12\x12\n\nwordsCount\x18\x01 \x01(\x05\"7\n\x0fQProcessMessage\x12\x12\n\nwordsCount\x18\x01 \x01(\t\x12\x10\n\x08resultId\x18\x02 \x01(\x05\"6\n\x0eQResultMessage\x12\x12\n\nwordsCount\x18\x01 \x01(\x05\x12\x10\n\x08resultId\x18\x02 \x01(\x05\x32r\n\x05\x43ount\x12\x33\n\x0cQueueProcess\x12\x0f.count.QRequest\x1a\x10.count.QResultId\"\x00\x12\x34\n\x0eQueueGetResult\x12\x10.count.QResultId\x1a\x0e.count.QResult\"\x00\x42$Z\"github.com/domage/grpc-queue/countb\x06proto3'
)




_QREQUEST = _descriptor.Descriptor(
  name='QRequest',
  full_name='count.QRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wordsToCount', full_name='count.QRequest.wordsToCount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=54,
)


_QRESULTID = _descriptor.Descriptor(
  name='QResultId',
  full_name='count.QResultId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultId', full_name='count.QResultId.resultId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=85,
)


_QRESULT = _descriptor.Descriptor(
  name='QResult',
  full_name='count.QResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wordsCount', full_name='count.QResult.wordsCount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=116,
)


_QPROCESSMESSAGE = _descriptor.Descriptor(
  name='QProcessMessage',
  full_name='count.QProcessMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wordsCount', full_name='count.QProcessMessage.wordsCount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resultId', full_name='count.QProcessMessage.resultId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=173,
)


_QRESULTMESSAGE = _descriptor.Descriptor(
  name='QResultMessage',
  full_name='count.QResultMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wordsCount', full_name='count.QResultMessage.wordsCount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resultId', full_name='count.QResultMessage.resultId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=229,
)

DESCRIPTOR.message_types_by_name['QRequest'] = _QREQUEST
DESCRIPTOR.message_types_by_name['QResultId'] = _QRESULTID
DESCRIPTOR.message_types_by_name['QResult'] = _QRESULT
DESCRIPTOR.message_types_by_name['QProcessMessage'] = _QPROCESSMESSAGE
DESCRIPTOR.message_types_by_name['QResultMessage'] = _QRESULTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QRequest = _reflection.GeneratedProtocolMessageType('QRequest', (_message.Message,), {
  'DESCRIPTOR' : _QREQUEST,
  '__module__' : 'count_pb2'
  # @@protoc_insertion_point(class_scope:count.QRequest)
  })
_sym_db.RegisterMessage(QRequest)

QResultId = _reflection.GeneratedProtocolMessageType('QResultId', (_message.Message,), {
  'DESCRIPTOR' : _QRESULTID,
  '__module__' : 'count_pb2'
  # @@protoc_insertion_point(class_scope:count.QResultId)
  })
_sym_db.RegisterMessage(QResultId)

QResult = _reflection.GeneratedProtocolMessageType('QResult', (_message.Message,), {
  'DESCRIPTOR' : _QRESULT,
  '__module__' : 'count_pb2'
  # @@protoc_insertion_point(class_scope:count.QResult)
  })
_sym_db.RegisterMessage(QResult)

QProcessMessage = _reflection.GeneratedProtocolMessageType('QProcessMessage', (_message.Message,), {
  'DESCRIPTOR' : _QPROCESSMESSAGE,
  '__module__' : 'count_pb2'
  # @@protoc_insertion_point(class_scope:count.QProcessMessage)
  })
_sym_db.RegisterMessage(QProcessMessage)

QResultMessage = _reflection.GeneratedProtocolMessageType('QResultMessage', (_message.Message,), {
  'DESCRIPTOR' : _QRESULTMESSAGE,
  '__module__' : 'count_pb2'
  # @@protoc_insertion_point(class_scope:count.QResultMessage)
  })
_sym_db.RegisterMessage(QResultMessage)


DESCRIPTOR._options = None

_COUNT = _descriptor.ServiceDescriptor(
  name='Count',
  full_name='count.Count',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=231,
  serialized_end=345,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueueProcess',
    full_name='count.Count.QueueProcess',
    index=0,
    containing_service=None,
    input_type=_QREQUEST,
    output_type=_QRESULTID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueueGetResult',
    full_name='count.Count.QueueGetResult',
    index=1,
    containing_service=None,
    input_type=_QRESULTID,
    output_type=_QRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COUNT)

DESCRIPTOR.services_by_name['Count'] = _COUNT

# @@protoc_insertion_point(module_scope)
