// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package count

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CountClient is the client API for Count service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CountClient interface {
	QueueProcess(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResultId, error)
	QueueGetResult(ctx context.Context, in *QResultId, opts ...grpc.CallOption) (*QResult, error)
}

type countClient struct {
	cc grpc.ClientConnInterface
}

func NewCountClient(cc grpc.ClientConnInterface) CountClient {
	return &countClient{cc}
}

func (c *countClient) QueueProcess(ctx context.Context, in *QRequest, opts ...grpc.CallOption) (*QResultId, error) {
	out := new(QResultId)
	err := c.cc.Invoke(ctx, "/count.Count/QueueProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *countClient) QueueGetResult(ctx context.Context, in *QResultId, opts ...grpc.CallOption) (*QResult, error) {
	out := new(QResult)
	err := c.cc.Invoke(ctx, "/count.Count/QueueGetResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CountServer is the server API for Count service.
// All implementations must embed UnimplementedCountServer
// for forward compatibility
type CountServer interface {
	QueueProcess(context.Context, *QRequest) (*QResultId, error)
	QueueGetResult(context.Context, *QResultId) (*QResult, error)
	mustEmbedUnimplementedCountServer()
}

// UnimplementedCountServer must be embedded to have forward compatible implementations.
type UnimplementedCountServer struct {
}

func (UnimplementedCountServer) QueueProcess(context.Context, *QRequest) (*QResultId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueProcess not implemented")
}
func (UnimplementedCountServer) QueueGetResult(context.Context, *QResultId) (*QResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueGetResult not implemented")
}
func (UnimplementedCountServer) mustEmbedUnimplementedCountServer() {}

// UnsafeCountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CountServer will
// result in compilation errors.
type UnsafeCountServer interface {
	mustEmbedUnimplementedCountServer()
}

func RegisterCountServer(s grpc.ServiceRegistrar, srv CountServer) {
	s.RegisterService(&Count_ServiceDesc, srv)
}

func _Count_QueueProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountServer).QueueProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/count.Count/QueueProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountServer).QueueProcess(ctx, req.(*QRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Count_QueueGetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QResultId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountServer).QueueGetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/count.Count/QueueGetResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountServer).QueueGetResult(ctx, req.(*QResultId))
	}
	return interceptor(ctx, in, info, handler)
}

// Count_ServiceDesc is the grpc.ServiceDesc for Count service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Count_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "count.Count",
	HandlerType: (*CountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueueProcess",
			Handler:    _Count_QueueProcess_Handler,
		},
		{
			MethodName: "QueueGetResult",
			Handler:    _Count_QueueGetResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "count.proto",
}
