// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: count.proto

package count

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type QRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WordsToCount string `protobuf:"bytes,1,opt,name=wordsToCount,proto3" json:"wordsToCount,omitempty"`
}

func (x *QRequest) Reset() {
	*x = QRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_count_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRequest) ProtoMessage() {}

func (x *QRequest) ProtoReflect() protoreflect.Message {
	mi := &file_count_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRequest.ProtoReflect.Descriptor instead.
func (*QRequest) Descriptor() ([]byte, []int) {
	return file_count_proto_rawDescGZIP(), []int{0}
}

func (x *QRequest) GetWordsToCount() string {
	if x != nil {
		return x.WordsToCount
	}
	return ""
}

type QResultId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultId int32 `protobuf:"varint,1,opt,name=resultId,proto3" json:"resultId,omitempty"`
}

func (x *QResultId) Reset() {
	*x = QResultId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_count_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QResultId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QResultId) ProtoMessage() {}

func (x *QResultId) ProtoReflect() protoreflect.Message {
	mi := &file_count_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QResultId.ProtoReflect.Descriptor instead.
func (*QResultId) Descriptor() ([]byte, []int) {
	return file_count_proto_rawDescGZIP(), []int{1}
}

func (x *QResultId) GetResultId() int32 {
	if x != nil {
		return x.ResultId
	}
	return 0
}

type QResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasResult  bool  `protobuf:"varint,1,opt,name=hasResult,proto3" json:"hasResult,omitempty"`
	WordsCount int32 `protobuf:"varint,2,opt,name=wordsCount,proto3" json:"wordsCount,omitempty"`
}

func (x *QResult) Reset() {
	*x = QResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_count_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QResult) ProtoMessage() {}

func (x *QResult) ProtoReflect() protoreflect.Message {
	mi := &file_count_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QResult.ProtoReflect.Descriptor instead.
func (*QResult) Descriptor() ([]byte, []int) {
	return file_count_proto_rawDescGZIP(), []int{2}
}

func (x *QResult) GetHasResult() bool {
	if x != nil {
		return x.HasResult
	}
	return false
}

func (x *QResult) GetWordsCount() int32 {
	if x != nil {
		return x.WordsCount
	}
	return 0
}

type QProcessMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WordsCount string `protobuf:"bytes,1,opt,name=wordsCount,proto3" json:"wordsCount,omitempty"`
	ResultId   int32  `protobuf:"varint,2,opt,name=resultId,proto3" json:"resultId,omitempty"`
}

func (x *QProcessMessage) Reset() {
	*x = QProcessMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_count_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QProcessMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QProcessMessage) ProtoMessage() {}

func (x *QProcessMessage) ProtoReflect() protoreflect.Message {
	mi := &file_count_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QProcessMessage.ProtoReflect.Descriptor instead.
func (*QProcessMessage) Descriptor() ([]byte, []int) {
	return file_count_proto_rawDescGZIP(), []int{3}
}

func (x *QProcessMessage) GetWordsCount() string {
	if x != nil {
		return x.WordsCount
	}
	return ""
}

func (x *QProcessMessage) GetResultId() int32 {
	if x != nil {
		return x.ResultId
	}
	return 0
}

type QResultMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WordsCount int32 `protobuf:"varint,1,opt,name=wordsCount,proto3" json:"wordsCount,omitempty"`
	ResultId   int32 `protobuf:"varint,2,opt,name=resultId,proto3" json:"resultId,omitempty"`
}

func (x *QResultMessage) Reset() {
	*x = QResultMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_count_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QResultMessage) ProtoMessage() {}

func (x *QResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_count_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QResultMessage.ProtoReflect.Descriptor instead.
func (*QResultMessage) Descriptor() ([]byte, []int) {
	return file_count_proto_rawDescGZIP(), []int{4}
}

func (x *QResultMessage) GetWordsCount() int32 {
	if x != nil {
		return x.WordsCount
	}
	return 0
}

func (x *QResultMessage) GetResultId() int32 {
	if x != nil {
		return x.ResultId
	}
	return 0
}

var File_count_proto protoreflect.FileDescriptor

var file_count_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2e, 0x0a, 0x08, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x54, 0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x54, 0x6f, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x27, 0x0a, 0x09, 0x51, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x64, 0x22, 0x47, 0x0a,
	0x07, 0x51, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x61, 0x73,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4d, 0x0a, 0x0f, 0x51, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x0e, 0x51, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x64, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x49, 0x64, 0x32, 0x72, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x0c,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x0f, 0x2e, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x51, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x64, 0x22,
	0x00, 0x12, 0x34, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x10, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x51, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x49, 0x64, 0x1a, 0x0e, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x51, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x67, 0x65, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_count_proto_rawDescOnce sync.Once
	file_count_proto_rawDescData = file_count_proto_rawDesc
)

func file_count_proto_rawDescGZIP() []byte {
	file_count_proto_rawDescOnce.Do(func() {
		file_count_proto_rawDescData = protoimpl.X.CompressGZIP(file_count_proto_rawDescData)
	})
	return file_count_proto_rawDescData
}

var file_count_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_count_proto_goTypes = []interface{}{
	(*QRequest)(nil),        // 0: count.QRequest
	(*QResultId)(nil),       // 1: count.QResultId
	(*QResult)(nil),         // 2: count.QResult
	(*QProcessMessage)(nil), // 3: count.QProcessMessage
	(*QResultMessage)(nil),  // 4: count.QResultMessage
}
var file_count_proto_depIdxs = []int32{
	0, // 0: count.Count.QueueProcess:input_type -> count.QRequest
	1, // 1: count.Count.QueueGetResult:input_type -> count.QResultId
	1, // 2: count.Count.QueueProcess:output_type -> count.QResultId
	2, // 3: count.Count.QueueGetResult:output_type -> count.QResult
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_count_proto_init() }
func file_count_proto_init() {
	if File_count_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_count_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_count_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QResultId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_count_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_count_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QProcessMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_count_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QResultMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_count_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_count_proto_goTypes,
		DependencyIndexes: file_count_proto_depIdxs,
		MessageInfos:      file_count_proto_msgTypes,
	}.Build()
	File_count_proto = out.File
	file_count_proto_rawDesc = nil
	file_count_proto_goTypes = nil
	file_count_proto_depIdxs = nil
}
