// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: count.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Count {

  /// <summary>Holder for reflection information generated from count.proto</summary>
  public static partial class CountReflection {

    #region Descriptor
    /// <summary>File descriptor for count.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CountReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgtjb3VudC5wcm90bxIFY291bnQiIAoIUVJlcXVlc3QSFAoMd29yZHNUb0Nv",
            "dW50GAEgASgJIh0KCVFSZXN1bHRJZBIQCghyZXN1bHRJZBgBIAEoBSIwCgdR",
            "UmVzdWx0EhEKCWhhc1Jlc3VsdBgBIAEoCBISCgp3b3Jkc0NvdW50GAIgASgF",
            "IjcKD1FQcm9jZXNzTWVzc2FnZRISCgp3b3Jkc0NvdW50GAEgASgJEhAKCHJl",
            "c3VsdElkGAIgASgFIjYKDlFSZXN1bHRNZXNzYWdlEhIKCndvcmRzQ291bnQY",
            "ASABKAUSEAoIcmVzdWx0SWQYAiABKAUycgoFQ291bnQSMwoMUXVldWVQcm9j",
            "ZXNzEg8uY291bnQuUVJlcXVlc3QaEC5jb3VudC5RUmVzdWx0SWQiABI0Cg5R",
            "dWV1ZUdldFJlc3VsdBIQLmNvdW50LlFSZXN1bHRJZBoOLmNvdW50LlFSZXN1",
            "bHQiAEIkWiJnaXRodWIuY29tL2RvbWFnZS9ncnBjLXF1ZXVlL2NvdW50YgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Count.QRequest), global::Count.QRequest.Parser, new[]{ "WordsToCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Count.QResultId), global::Count.QResultId.Parser, new[]{ "ResultId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Count.QResult), global::Count.QResult.Parser, new[]{ "HasResult", "WordsCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Count.QProcessMessage), global::Count.QProcessMessage.Parser, new[]{ "WordsCount", "ResultId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Count.QResultMessage), global::Count.QResultMessage.Parser, new[]{ "WordsCount", "ResultId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class QRequest : pb::IMessage<QRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QRequest> _parser = new pb::MessageParser<QRequest>(() => new QRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Count.CountReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QRequest(QRequest other) : this() {
      wordsToCount_ = other.wordsToCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QRequest Clone() {
      return new QRequest(this);
    }

    /// <summary>Field number for the "wordsToCount" field.</summary>
    public const int WordsToCountFieldNumber = 1;
    private string wordsToCount_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string WordsToCount {
      get { return wordsToCount_; }
      set {
        wordsToCount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WordsToCount != other.WordsToCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (WordsToCount.Length != 0) hash ^= WordsToCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WordsToCount.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WordsToCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WordsToCount.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WordsToCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (WordsToCount.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WordsToCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QRequest other) {
      if (other == null) {
        return;
      }
      if (other.WordsToCount.Length != 0) {
        WordsToCount = other.WordsToCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            WordsToCount = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            WordsToCount = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QResultId : pb::IMessage<QResultId>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QResultId> _parser = new pb::MessageParser<QResultId>(() => new QResultId());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QResultId> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Count.CountReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QResultId() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QResultId(QResultId other) : this() {
      resultId_ = other.resultId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QResultId Clone() {
      return new QResultId(this);
    }

    /// <summary>Field number for the "resultId" field.</summary>
    public const int ResultIdFieldNumber = 1;
    private int resultId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ResultId {
      get { return resultId_; }
      set {
        resultId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QResultId);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QResultId other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResultId != other.ResultId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResultId != 0) hash ^= ResultId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResultId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResultId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResultId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResultId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QResultId other) {
      if (other == null) {
        return;
      }
      if (other.ResultId != 0) {
        ResultId = other.ResultId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResultId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ResultId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QResult : pb::IMessage<QResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QResult> _parser = new pb::MessageParser<QResult>(() => new QResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Count.CountReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QResult(QResult other) : this() {
      hasResult_ = other.hasResult_;
      wordsCount_ = other.wordsCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QResult Clone() {
      return new QResult(this);
    }

    /// <summary>Field number for the "hasResult" field.</summary>
    public const int HasResultFieldNumber = 1;
    private bool hasResult_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasResult {
      get { return hasResult_; }
      set {
        hasResult_ = value;
      }
    }

    /// <summary>Field number for the "wordsCount" field.</summary>
    public const int WordsCountFieldNumber = 2;
    private int wordsCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int WordsCount {
      get { return wordsCount_; }
      set {
        wordsCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HasResult != other.HasResult) return false;
      if (WordsCount != other.WordsCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasResult != false) hash ^= HasResult.GetHashCode();
      if (WordsCount != 0) hash ^= WordsCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasResult != false) {
        output.WriteRawTag(8);
        output.WriteBool(HasResult);
      }
      if (WordsCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(WordsCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasResult != false) {
        output.WriteRawTag(8);
        output.WriteBool(HasResult);
      }
      if (WordsCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(WordsCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasResult != false) {
        size += 1 + 1;
      }
      if (WordsCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WordsCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QResult other) {
      if (other == null) {
        return;
      }
      if (other.HasResult != false) {
        HasResult = other.HasResult;
      }
      if (other.WordsCount != 0) {
        WordsCount = other.WordsCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            HasResult = input.ReadBool();
            break;
          }
          case 16: {
            WordsCount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            HasResult = input.ReadBool();
            break;
          }
          case 16: {
            WordsCount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QProcessMessage : pb::IMessage<QProcessMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QProcessMessage> _parser = new pb::MessageParser<QProcessMessage>(() => new QProcessMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QProcessMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Count.CountReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QProcessMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QProcessMessage(QProcessMessage other) : this() {
      wordsCount_ = other.wordsCount_;
      resultId_ = other.resultId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QProcessMessage Clone() {
      return new QProcessMessage(this);
    }

    /// <summary>Field number for the "wordsCount" field.</summary>
    public const int WordsCountFieldNumber = 1;
    private string wordsCount_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string WordsCount {
      get { return wordsCount_; }
      set {
        wordsCount_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resultId" field.</summary>
    public const int ResultIdFieldNumber = 2;
    private int resultId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ResultId {
      get { return resultId_; }
      set {
        resultId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QProcessMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QProcessMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WordsCount != other.WordsCount) return false;
      if (ResultId != other.ResultId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (WordsCount.Length != 0) hash ^= WordsCount.GetHashCode();
      if (ResultId != 0) hash ^= ResultId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WordsCount.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WordsCount);
      }
      if (ResultId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ResultId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WordsCount.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WordsCount);
      }
      if (ResultId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ResultId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (WordsCount.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WordsCount);
      }
      if (ResultId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QProcessMessage other) {
      if (other == null) {
        return;
      }
      if (other.WordsCount.Length != 0) {
        WordsCount = other.WordsCount;
      }
      if (other.ResultId != 0) {
        ResultId = other.ResultId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            WordsCount = input.ReadString();
            break;
          }
          case 16: {
            ResultId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            WordsCount = input.ReadString();
            break;
          }
          case 16: {
            ResultId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class QResultMessage : pb::IMessage<QResultMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QResultMessage> _parser = new pb::MessageParser<QResultMessage>(() => new QResultMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QResultMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Count.CountReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QResultMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QResultMessage(QResultMessage other) : this() {
      wordsCount_ = other.wordsCount_;
      resultId_ = other.resultId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QResultMessage Clone() {
      return new QResultMessage(this);
    }

    /// <summary>Field number for the "wordsCount" field.</summary>
    public const int WordsCountFieldNumber = 1;
    private int wordsCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int WordsCount {
      get { return wordsCount_; }
      set {
        wordsCount_ = value;
      }
    }

    /// <summary>Field number for the "resultId" field.</summary>
    public const int ResultIdFieldNumber = 2;
    private int resultId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ResultId {
      get { return resultId_; }
      set {
        resultId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QResultMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QResultMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WordsCount != other.WordsCount) return false;
      if (ResultId != other.ResultId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (WordsCount != 0) hash ^= WordsCount.GetHashCode();
      if (ResultId != 0) hash ^= ResultId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WordsCount != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(WordsCount);
      }
      if (ResultId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ResultId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WordsCount != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(WordsCount);
      }
      if (ResultId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ResultId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (WordsCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WordsCount);
      }
      if (ResultId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResultId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QResultMessage other) {
      if (other == null) {
        return;
      }
      if (other.WordsCount != 0) {
        WordsCount = other.WordsCount;
      }
      if (other.ResultId != 0) {
        ResultId = other.ResultId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            WordsCount = input.ReadInt32();
            break;
          }
          case 16: {
            ResultId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            WordsCount = input.ReadInt32();
            break;
          }
          case 16: {
            ResultId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
